spring:
  threads:
    virtual:
      enabled: true
github:
  api:
    repos-endpoint: https://api.github.com/users/{username}/repos
    branches-endpoint: https://api.github.com/repos/{owner}/{repo}/branches